/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timer;

import java.awt.Color;
import static java.lang.Thread.sleep;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/**
 *
 * @author laurentera_sd2082
 */
public class Timers extends javax.swing.JFrame {

    static int seconds = 0;
    static int minutes = 0;
    static int hours = 0;
    static int secondsCountDown = 10;
    static int secondsCountUp = 0;

    static boolean stateStopWatch = true;
    static boolean stateCountDown = true;
    static boolean stateCountUp = true;

    /**
     * Creates new form Timers
     */
    public Timers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        CountUp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        countup = new javax.swing.JLabel();
        startBtnCounterUp = new javax.swing.JButton();
        stopBtnCounterUp = new javax.swing.JButton();
        resetBtnCounterUp = new javax.swing.JButton();
        CurrentTime = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        GetCurrentTime = new javax.swing.JButton();
        testCurrentTime = new javax.swing.JLabel();
        CountDown = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        startBtnCounterDown = new javax.swing.JButton();
        stopBtnCounterDown = new javax.swing.JButton();
        resetBtnCounterDown = new javax.swing.JButton();
        countdown = new javax.swing.JLabel();
        StopWatch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        startBtnStopWatch = new javax.swing.JButton();
        stopBtnStopWatch = new javax.swing.JButton();
        resetBtnStopWatch = new javax.swing.JButton();
        hourStopWatch = new javax.swing.JLabel();
        secondStopWatch = new javax.swing.JLabel();
        minuteStopWatch = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CountUp.setBackground(new java.awt.Color(255, 255, 255));
        CountUp.setFocusCycleRoot(true);

        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("COUNT UP");

        countup.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        countup.setForeground(new java.awt.Color(255, 153, 153));
        countup.setText("0");

        startBtnCounterUp.setText("START");
        startBtnCounterUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnCounterUpActionPerformed(evt);
            }
        });

        stopBtnCounterUp.setText("STOP");
        stopBtnCounterUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnCounterUpActionPerformed(evt);
            }
        });

        resetBtnCounterUp.setText("RESET");
        resetBtnCounterUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnCounterUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CountUpLayout = new javax.swing.GroupLayout(CountUp);
        CountUp.setLayout(CountUpLayout);
        CountUpLayout.setHorizontalGroup(
            CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountUpLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(startBtnCounterUp)
                .addGap(18, 18, 18)
                .addGroup(CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(CountUpLayout.createSequentialGroup()
                        .addGroup(CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(countup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stopBtnCounterUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(resetBtnCounterUp)))
                .addGap(32, 32, 32))
        );
        CountUpLayout.setVerticalGroup(
            CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CountUpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(countup, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(CountUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtnCounterUp)
                    .addComponent(stopBtnCounterUp)
                    .addComponent(resetBtnCounterUp))
                .addGap(24, 24, 24))
        );

        CurrentTime.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CURRENT TIME");

        GetCurrentTime.setText("GET TIME");
        GetCurrentTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCurrentTimeActionPerformed(evt);
            }
        });

        testCurrentTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        testCurrentTime.setForeground(new java.awt.Color(255, 255, 255));
        testCurrentTime.setText("0000-00-00 00:00:00");

        javax.swing.GroupLayout CurrentTimeLayout = new javax.swing.GroupLayout(CurrentTime);
        CurrentTime.setLayout(CurrentTimeLayout);
        CurrentTimeLayout.setHorizontalGroup(
            CurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentTimeLayout.createSequentialGroup()
                .addGroup(CurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CurrentTimeLayout.createSequentialGroup()
                        .addGroup(CurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CurrentTimeLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel2))
                            .addGroup(CurrentTimeLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(GetCurrentTime)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CurrentTimeLayout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(testCurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CurrentTimeLayout.setVerticalGroup(
            CurrentTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrentTimeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addComponent(testCurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(GetCurrentTime)
                .addGap(28, 28, 28))
        );

        CountDown.setBackground(new java.awt.Color(255, 255, 0));

        jLabel3.setText("COUNT DOWN");

        startBtnCounterDown.setText("START");
        startBtnCounterDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnCounterDownActionPerformed(evt);
            }
        });

        stopBtnCounterDown.setText("STOP");
        stopBtnCounterDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnCounterDownActionPerformed(evt);
            }
        });

        resetBtnCounterDown.setText("RESET");
        resetBtnCounterDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnCounterDownActionPerformed(evt);
            }
        });

        countdown.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        countdown.setText("10");

        javax.swing.GroupLayout CountDownLayout = new javax.swing.GroupLayout(CountDown);
        CountDown.setLayout(CountDownLayout);
        CountDownLayout.setHorizontalGroup(
            CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CountDownLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(startBtnCounterDown)
                .addGap(18, 18, 18)
                .addGroup(CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countdown, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CountDownLayout.createSequentialGroup()
                        .addGroup(CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(CountDownLayout.createSequentialGroup()
                                .addComponent(stopBtnCounterDown)
                                .addGap(4, 4, 4)))
                        .addGap(18, 18, 18)
                        .addComponent(resetBtnCounterDown)))
                .addGap(34, 34, 34))
        );
        CountDownLayout.setVerticalGroup(
            CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CountDownLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(62, 62, 62)
                .addComponent(countdown, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CountDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtnCounterDown)
                    .addComponent(stopBtnCounterDown)
                    .addComponent(resetBtnCounterDown))
                .addGap(22, 22, 22))
        );

        StopWatch.setBackground(new java.awt.Color(100, 240, 240));

        jLabel1.setText("STOPWATCH");

        startBtnStopWatch.setText("START");
        startBtnStopWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnStopWatchActionPerformed(evt);
            }
        });

        stopBtnStopWatch.setText("STOP");
        stopBtnStopWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnStopWatchActionPerformed(evt);
            }
        });

        resetBtnStopWatch.setText("RESET");
        resetBtnStopWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnStopWatchActionPerformed(evt);
            }
        });

        hourStopWatch.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 45)); // NOI18N
        hourStopWatch.setText(" 00");

        secondStopWatch.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 45)); // NOI18N
        secondStopWatch.setText(":  00");

        minuteStopWatch.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 45)); // NOI18N
        minuteStopWatch.setText(":  00");

        javax.swing.GroupLayout StopWatchLayout = new javax.swing.GroupLayout(StopWatch);
        StopWatch.setLayout(StopWatchLayout);
        StopWatchLayout.setHorizontalGroup(
            StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(StopWatchLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(startBtnStopWatch)
                    .addGap(18, 18, 18)
                    .addComponent(stopBtnStopWatch)
                    .addGap(18, 18, 18)
                    .addComponent(resetBtnStopWatch)
                    .addContainerGap(30, Short.MAX_VALUE))
                .addGroup(StopWatchLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hourStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(minuteStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(secondStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
            .addGroup(StopWatchLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        StopWatchLayout.setVerticalGroup(
            StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StopWatchLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minuteStopWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(StopWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtnStopWatch)
                    .addComponent(stopBtnStopWatch)
                    .addComponent(resetBtnStopWatch))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StopWatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CountDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CountUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StopWatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CountUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CountDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void startBtnStopWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnStopWatchActionPerformed
        stateStopWatch = true;

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (stateStopWatch == true) {
                        try {

                            if (seconds == 60) {
                                seconds = 0;
                                minutes++;
                            }
                            if (minutes == 60) {
                                seconds = 0;
                                hours++;
                            }

                            secondStopWatch.setText(": " + seconds);
                            minuteStopWatch.setText(": " + minutes);
                            hourStopWatch.setText("" + hours);
                            seconds++;
                            sleep(1000);
                        } catch (InterruptedException e) {
                            System.out.println(e.getMessage());
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_startBtnStopWatchActionPerformed

    private void stopBtnStopWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnStopWatchActionPerformed
        stateStopWatch = false;
    }//GEN-LAST:event_stopBtnStopWatchActionPerformed

    private void resetBtnStopWatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnStopWatchActionPerformed
        stateStopWatch = false;

        seconds = 0;
        minutes = 0;
        hours = 0;

        secondStopWatch.setText(":" + seconds);
        minuteStopWatch.setText(":" + minutes);
        hourStopWatch.setText("" + hours);


    }//GEN-LAST:event_resetBtnStopWatchActionPerformed

    private void startBtnCounterDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnCounterDownActionPerformed

        stateCountDown = true;

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (stateCountDown == true) {
                        try {

                            if (secondsCountDown != 0) {;
                                secondsCountDown--;
                                sleep(1000);
                            } else if (secondsCountDown == 0) {
                                CountDown.setBackground(Color.white);
                            }
                            countdown.setText(" " + secondsCountDown);
                            
                        } catch (InterruptedException e) {
                            System.out.println(e.getMessage());
                        }

                    } else {
                        break;
                    }

                }
            }
        };
        t.start();
    }//GEN-LAST:event_startBtnCounterDownActionPerformed

    private void startBtnCounterUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnCounterUpActionPerformed

        stateCountUp = true;

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    if (stateCountUp == true) {
                        try {
                            secondsCountUp++;  
                            if (secondsCountUp == 11) {
                                CountUp.setBackground(Color.black);              
                                break;                    
                            }
                            sleep(1000);
                            countup.setText(" " + secondsCountUp);

                        } catch (InterruptedException e) {
                            System.out.println(e.getMessage());
                        }
                    } else {
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_startBtnCounterUpActionPerformed

    private void GetCurrentTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCurrentTimeActionPerformed

        Thread t = new Thread() {
            public void run() {
                for (;;) {
                    try {
                        Date date = new Date();
                        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd  hh:mm:ss");
                        testCurrentTime.setText(dateFormat.format(date));
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                        break;
                    }
                }
            }
        };
        t.start();
    }//GEN-LAST:event_GetCurrentTimeActionPerformed

    private void stopBtnCounterDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnCounterDownActionPerformed
        stateCountDown = false;
    }//GEN-LAST:event_stopBtnCounterDownActionPerformed

    private void resetBtnCounterDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnCounterDownActionPerformed
        stateCountDown = false;
        secondsCountDown = 10;
        countdown.setText(" " + secondsCountDown);
        CountDown.setBackground(Color.yellow);
    }//GEN-LAST:event_resetBtnCounterDownActionPerformed

    private void stopBtnCounterUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnCounterUpActionPerformed
        stateCountUp = false;
    }//GEN-LAST:event_stopBtnCounterUpActionPerformed

    private void resetBtnCounterUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnCounterUpActionPerformed
        stateCountUp = false;
        secondsCountUp = 0;
        countup.setText(" " + secondsCountUp);
        CountUp.setBackground(Color.WHITE);


    }//GEN-LAST:event_resetBtnCounterUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CountDown;
    private javax.swing.JPanel CountUp;
    private javax.swing.JPanel CurrentTime;
    private javax.swing.JButton GetCurrentTime;
    private javax.swing.JPanel StopWatch;
    private javax.swing.JLabel countdown;
    private javax.swing.JLabel countup;
    private javax.swing.JLabel hourStopWatch;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel minuteStopWatch;
    private javax.swing.JButton resetBtnCounterDown;
    private javax.swing.JButton resetBtnCounterUp;
    private javax.swing.JButton resetBtnStopWatch;
    private javax.swing.JLabel secondStopWatch;
    private javax.swing.JButton startBtnCounterDown;
    private javax.swing.JButton startBtnCounterUp;
    private javax.swing.JButton startBtnStopWatch;
    private javax.swing.JButton stopBtnCounterDown;
    private javax.swing.JButton stopBtnCounterUp;
    private javax.swing.JButton stopBtnStopWatch;
    private javax.swing.JLabel testCurrentTime;
    // End of variables declaration//GEN-END:variables
}
